QLSVVV/Models/Teacher.cs
namespace QLSVVV.Models
{
    public class Teacher
    {
        public int Id { get; set; }
        public String? Name { get; set; }
        public DateTime? DoB { get; set; }
        public string? Major { get; set; }
        public Teacher()
        {
        }
    }
}

QLSVVV/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLSVVV.Data;
using QLSVVV.Models;

namespace QLSVVV.Controllers
{
    /*  [Authorize(Roles = "Admin")]
      [Authorize(Roles = "Student")]
      [Authorize(Roles = "Teacher")]*/
   
    public class ClassesController : Controller
    {
        private readonly QLSVVVContext _context;

        public ClassesController(QLSVVVContext context)
        {
            _context = context;
        }

        // GET: Classes
        public async Task<IActionResult>  Index()
        {
              return _context.Class != null ? 
                          View(await _context.Class.ToListAsync()) :
                          Problem("Entity set 'QLSVVVContext.Class'  is null.");
        }

        // GET: Classes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Class == null)
            {
                return NotFound();
            }

            var @class = await _context.Class
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // GET: Classes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Major,Lecturer")] Class @class)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@class);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ManageClass));
            }
            return View(@class);
        }

        // GET: Classes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Class == null)
            {
                return NotFound();
            }

            var @class = await _context.Class.FindAsync(id);
            if (@class == null)
            {
                return NotFound();
            }
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Major,Lecturer")] Class @class)
        {
            if (id != @class.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ManageClass));
            }
            return View(@class);
        }

        // GET: Classes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Class == null)
            {
                return NotFound();
            }

            var @class = await _context.Class
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost,  ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Class == null)
            {
                return Problem("Entity set 'QLSVVVContext.Class'  is null.");
            }
            var @class = await _context.Class.FindAsync(id);
            if (@class != null)
            {
                _context.Class.Remove(@class);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ManageClass));
        }

        private bool ClassExists(int id)
        {
          return (_context.Class?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> ManageClass()
        {
            return View(await _context.Class.ToListAsync());
        }
        public async Task<IActionResult> ViewClass()
        {
            return View(await _context.Class.ToListAsync());
        }
        public async Task<IActionResult> ViewClassStudent()
        {
            return View(await _context.Class.ToListAsync());
        }
    }
}

QLSVVV/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLSVVV.Data;
using QLSVVV.Models;

namespace QLSVVV.Controllers
{
    /*  [Authorize(Roles = "Admin")]
      [Authorize(Roles = "Student")]
      [Authorize(Roles = "Teacher")]*/
    public class StudentsController : Controller
    {
        private readonly QLSVVVContext _context;

        public StudentsController(QLSVVVContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
              return _context.Student != null ? 
                          View(await _context.Student.ToListAsync()) :
                          Problem("Entity set 'QLSVVVContext.Student'  is null.");
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DoB,Address,Major")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ManageStudent));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DoB,Address,Major")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ManageStudent));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Student == null)
            {
                return Problem("Entity set 'QLSVVVContext.Student'  is null.");
            }
            var student = await _context.Student.FindAsync(id);
            if (student != null)
            {
                _context.Student.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ManageStudent));
        }

        private bool StudentExists(int id)
        {
          return (_context.Student?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> ManageStudent()
        {
            return View(await _context.Student.ToListAsync());
        }
        public async Task<IActionResult> ViewStudent()
        {
            return View(await _context.Student.ToListAsync());
        }
    }

}

QLSVVV/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLSVVV.Data;
using QLSVVV.Models;

namespace QLSVVV.Controllers
{
    /*  [Authorize(Roles = "Admin")]
      [Authorize(Roles = "Student")]
      [Authorize(Roles = "Teacher")]*/
    public class TeachersController : Controller
    {
        private readonly QLSVVVContext _context;

        public TeachersController(QLSVVVContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
              return _context.Teacher != null ? 
                          View(await _context.Teacher.ToListAsync()) :
                          Problem("Entity set 'QLSVVVContext.Teacher'  is null.");
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Teacher == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DoB,Major")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ManageTeacher));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Teacher == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DoB,Major")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ManageTeacher));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Teacher == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Teacher == null)
            {
                return Problem("Entity set 'QLSVVVContext.Teacher'  is null.");
            }
            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher != null)
            {
                _context.Teacher.Remove(teacher);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ManageTeacher));
        }

        private bool TeacherExists(int id)
        {
          return (_context.Teacher?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> ManageTeacher()
        {
            return View(await _context.Teacher.ToListAsync());
        }
        public async Task<IActionResult> ViewTeacher()
        {
            return View(await _context.Teacher.ToListAsync());
        }
    }
}

QLSVVV/Views/Teachers/Create.cshtml
@model QLSVVV.Models.Teacher

@{
    ViewData["Title"] = "Create";
}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f9;
        color: #333;
        margin: 0;
        padding: 20px;
    }

    h1, h4 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 20px;
    }

    .row {
        display: flex;
        justify-content: center;
    }

    .col-md-4 {
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .control-label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        transition: border-color 0.3s, box-shadow 0.3s;
    }

        .form-control:focus {
            border-color: #007bff;
            box-shadow: 0 0 8px rgba(0, 123, 255, 0.5);
        }

    .text-danger {
        color: #dc3545;
        font-size: 0.9em;
    }

    .btn-primary {
        background-color: #3498db;
        border: none;
        color: #fff;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        border: 2px solid #007bff;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        transition: background-color 0.3s;
        margin-left: 90px;
    }

        .btn-primary:hover {
            background-color: #fff;
            color: #3498db;
            font-weight: bold;
        }

        .btn-primary:focus {
            outline: none;
        }

    .form-actions {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }

    ul {
        list-style-type: none;
        padding: 0;
        text-align: center;
        margin-top: 20px;
    }

        ul li {
            display: inline-block;
        }

    .btn {
        display: inline-block;
        padding: 8px 16px;
        color: #fff;
        background-color: #3498db;
        text-decoration: none;
        border-radius: 4px;
        transition: background-color 0.3s;
        margin-right: 5px;
        border: 2px solid #007bff;
    }

        .btn:hover {
            background-color: #fff;
            color: #3498db;
            font-weight: bold;
            text-decoration:none;
        }
</style>
<h1>Create Teacher</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoB" class="control-label"></label>
                <input asp-for="DoB" class="form-control" />
                <span asp-validation-for="DoB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Major" class="control-label"></label>
                <input asp-for="Major" class="form-control" />
                <span asp-validation-for="Major" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input  type="submit" value="Create" class=" btn-primary" />
            </div>
        </form>
    </div>
</div>

<div> 
    <ul><li> <a class="btn btn-sm" asp-controller="Teachers" asp-action="ManageTeacher">Back To List</a></li></ul>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QLSVVV/Views/Teachers/Edit.cshtml
@model QLSVVV.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f9;
        color: #333;
        margin: 0;
        padding: 20px;
    }

    h1, h4 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 20px;
    }

    .row {
        display: flex;
        justify-content: center;
    }

    .col-md-4 {
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .control-label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

        .form-control:focus {
            border-color: #007bff;
            box-shadow: 0 0 8px rgba(0, 123, 255, 0.25);
        }

    .text-danger {
        color: #dc3545;
        font-size: 0.9em;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        transition: background-color 0.3s;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

        .btn-primary:focus {
            outline: none;
        }

    .form-actions {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }
</style>
<h1>Edit Teacher</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoB" class="control-label"></label>
                <input asp-for="DoB" class="form-control" />
                <span asp-validation-for="DoB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Major" class="control-label"></label>
                <input asp-for="Major" class="form-control" />
                <span asp-validation-for="Major" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Teachers" asp-action="ManageTeacher">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

QLSVVV/Views/Teachers/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Teacher Dashboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .logout-container {
            text-align: right;
            margin-bottom: 20px;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            color: white;
            background-color: #dc3545;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s;
        }

            .btn:hover {
                background-color: #c82333;
            }

        .btn-danger {
            display: inline-block;
            background-color: #fff;
            padding: 10px 20px;
            font-size: 16px;
            color: #c82333;
            text-decoration: none;
            border: 2px solid #c82333;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
            cursor: pointer;
        }

            .btn-danger:hover {
                background-color: #c82333;
            }


        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #2c3e50;
            margin-bottom: 30px;
        }

        .list-group {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .list-group-item {
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 4px;
            background-color: #3498db;
            transition: background-color 0.3s, color 0.3s;
        }

            .list-group-item a {
                text-decoration: none;
                color: #fff;
                display: block;
                width: 100%;
            }

            .list-group-item:hover {
                background-color: #3498db;
            }

            .list-group-item a:hover {
                color: #000;
            }
    </style>
</head>
<body>

    <div class="logout-container">
        <a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
    </div>
    <div class="container">
        <h1>Welcome To HomePage,Teacher!</h1>
        <ul class="list-group">
            <li class="list-group-item list-group-item-action list-group-item-warning"><a href="@Url.Action("ViewClass", "Classes")">View Classes</a></li>
            <li class="list-group-item list-group-item-action list-group-item-warning"><a href="@Url.Action("ViewStudent", "Students")">View Students</a></li>
            <li class="list-group-item list-group-item-action list-group-item-warning"><a href="@Url.Action("ViewCourse", "Courses")">View Courses</a></li>
        </ul>
    </div>
 
</body>
</html>

QLSVVV/Views/Teachers/ViewTeacher.cshtml
@model IEnumerable<QLSVVV.Models.Teacher>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa;
        color: #333;
        margin: 0;
        padding: 20px;
    }

    h1 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 30px;
    }

    .search-container {
        text-align: center;
        margin-bottom: 20px;
    }

    .search-input {
        width: 250px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-right: 10px;
    }

    .search-btn {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        .search-btn:hover {
            background-color: #0056b3;
        }

    .table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 4px;
        overflow: hidden;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }

        .table th, .table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .table thead {
            background-color: #f8f9fa;
        }

        .table tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table tbody tr:hover {
            background-color: #e9ecef;
        }

    .btn {
        display: inline-block;
        padding: 10px 20px;
        color: #fff;
        background-color: #007bff;
        text-decoration: none;
        border-radius: 4px;
        margin-top: 20px;
        text-align: center;
    }

        .btn:hover {
            background-color: #0056b3;
        }

    ul {
        list-style-type: none;
        padding: 0;
        text-align: center;
    }

        ul li {
            display: inline-block;
        }
</style>
<h1>Welcome to Teacher List, Student!!</h1>

<!-- Search container -->
<div class="search-container">
    <input type="text" id="searchInput" class="search-input" placeholder="Search by Name...">
    <button onclick="search()" class="search-btn">Search</button>
</div>

<!-- Teacher table -->
<table class="table">
    <!-- Table header -->
    <thead>
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Date of Birth</td>
            <td>Major</td>
        </tr>
    </thead>
    <!-- Table body -->
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.DoB</td>
                <td>@item.Major</td>
            </tr>
        }
    </tbody>
</table>

<!-- Back to HomePage button -->
<ul>
    <li><a class="btn btn-sm btn-primary" asp-controller="Students" asp-action="Index">Back to HomePage</a></li>
</ul>

<script>
    function search() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.querySelector(".table");
        tr = table.getElementsByTagName("tr");

        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1]; // Search in the second column (Name column)
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>