QLSVVV/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLSVVV.Data;
using QLSVVV.Models;


namespace QLSVVV.Controllers
{
    /*  [Authorize(Roles = "Admin")]
      [Authorize(Roles = "Student")]
      [Authorize(Roles = "Teacher")]*/
  
    public class CoursesController : Controller
    {
        private readonly QLSVVVContext _context;

        public CoursesController(QLSVVVContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
              return _context.Course != null ? 
                          View(await _context.Course.ToListAsync()) :
                          Problem("Entity set 'QLSVVVContext.Course'  is null.");
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Class,DateStart,DateEnd,Major,Lecturer")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ManageCourse));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Class,DateStart,DateEnd,Major,Lecturer")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ManageCourse));
            }
            return View(course);
        }
        public IActionResult ViewStudentlnCourse(int id)
        {
            var course = _context.Course
                .Include(c => c.CourseStudent)
                .ThenInclude(cs => cs.Student)
                .FirstOrDefault(c => c.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            ViewBag.AllStudents = _context.Student.ToList();

            return View(course);
        }

        public IActionResult EditCourse(int id)
        {
            var course = _context.Course
                .Include(c => c.CourseStudent)
                .ThenInclude(cs => cs.Student)
                .FirstOrDefault(c => c.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            ViewBag.AllStudents = _context.Student.ToList();

            return View(course);
        }

        [HttpPost]
        public IActionResult AddStudentToCourse(int courseId, int studentId)
        {
            var course = _context.Course
                .Include(c => c.CourseStudent)
                .FirstOrDefault(c => c.Id == courseId);

            var student = _context.Student.FirstOrDefault(s => s.Id == studentId);

            if (course != null && student != null)
            {
                course.CourseStudent.Add(new CourseStudent { CourseId = courseId, StudentId = studentId });
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(EditCourse), new { id = courseId });
        }

        [HttpPost]
        public IActionResult RemoveStudentFromCourse(int courseId, int studentId)
        {
            var course = _context.Course
                .Include(c => c.CourseStudent)
                .FirstOrDefault(c => c.Id == courseId);

            var student = _context.Student.FirstOrDefault(s => s.Id == studentId);

            if (course != null && student != null)
            {
                var courseStudent = course.CourseStudent.FirstOrDefault(cs => cs.StudentId == studentId);
                if (courseStudent != null)
                {
                    course.CourseStudent.Remove(courseStudent);
                    _context.SaveChanges();
                }
            }

            return RedirectToAction(nameof(EditCourse), new { id = courseId });
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'QLSVVVContext.Course'  is null.");
            }
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ManageCourse));
        }

        private bool CourseExists(int id)
        {
          return (_context.Course?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> ManageCourse()
        {
            return View(await _context.Course.ToListAsync());
        }
        
        public async Task<IActionResult> ViewCourse()
        {
            return View(await _context.Course.ToListAsync());
        }
        public async Task<IActionResult> ViewCourseStudent()
        {
            return View(await _context.Course.ToListAsync());
        }
        
        
    }
}

QLSVVV/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLSVVV.Data;
using QLSVVV.Models;

namespace QLSVVV.Controllers
{
    /*  [Authorize(Roles = "Admin")]
      [Authorize(Roles = "Student")]
      [Authorize(Roles = "Teacher")]*/
    public class StudentsController : Controller
    {
        private readonly QLSVVVContext _context;

        public StudentsController(QLSVVVContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
              return _context.Student != null ? 
                          View(await _context.Student.ToListAsync()) :
                          Problem("Entity set 'QLSVVVContext.Student'  is null.");
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DoB,Address,Major")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ManageStudent));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DoB,Address,Major")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ManageStudent));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Student == null)
            {
                return Problem("Entity set 'QLSVVVContext.Student'  is null.");
            }
            var student = await _context.Student.FindAsync(id);
            if (student != null)
            {
                _context.Student.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ManageStudent));
        }

        private bool StudentExists(int id)
        {
          return (_context.Student?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> ManageStudent()
        {
            return View(await _context.Student.ToListAsync());
        }
        public async Task<IActionResult> ViewStudent()
        {
            return View(await _context.Student.ToListAsync());
        }
    }

}

QLSVVV/Views/Courses/Create.cshtml
@model QLSVVV.Models.Course

@{
    ViewData["Title"] = "Create";
}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f9;
        color: #333;
        margin: 0;
        padding: 20px;
    }

    h1, h4 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 20px;
    }

    .row {
        display: flex;
        justify-content: center;
    }

    .col-md-4 {
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .control-label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        transition: border-color 0.3s, box-shadow 0.3s;
    }

        .form-control:focus {
            border-color: #007bff;
            box-shadow: 0 0 8px rgba(0, 123, 255, 0.5);
        }

    .text-danger {
        color: #dc3545;
        font-size: 0.9em;
    }

    .btn-primary {
        background-color: #3498db;
        border: none;
        color: #fff;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        border: 2px solid #007bff;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        transition: background-color 0.3s;
        margin-left: 90px;
    }

        .btn-primary:hover {
            background-color: #fff;
            color: #3498db;
            font-weight: bold;
        }

        .btn-primary:focus {
            outline: none;
        }

    .form-actions {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }

    ul {
        list-style-type: none;
        padding: 0;
        text-align: center;
        margin-top: 20px;
    }

        ul li {
            display: inline-block;
        }

    .btn {
        display: inline-block;
        padding: 8px 16px;
        color: #fff;
        background-color: #3498db;
        text-decoration: none;
        border-radius: 4px;
        transition: background-color 0.3s;
        margin-right: 5px;
        border: 2px solid #007bff;
    }

        .btn:hover {
            background-color: #fff;
            color: #3498db;
            font-weight: bold;
            text-decoration: none;
        }
</style>
<h1>Create Course</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label"></label>
                <input asp-for="DateStart" class="form-control" type="date" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" type="date" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Major" class="control-label"></label>
                <input asp-for="Major" class="form-control" />
                <span asp-validation-for="Major" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lecturer" class="control-label"></label>
                <input asp-for="Lecturer" class="form-control" />
                <span asp-validation-for="Lecturer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class=" btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <ul><li> <a class="btn btn-sm" asp-controller="Courses" asp-action="ManageCourse">Back To List</a></li></ul>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QLSVVV/Views/Courses/Edit.cshtml
@model QLSVVV.Models.Course

@{
    ViewData["Title"] = "Edit";
}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f9;
        color: #333;
        margin: 0;
        padding: 20px;
    }

    h1, h4 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 20px;
    }

    .row {
        display: flex;
        justify-content: center;
    }

    .col-md-4 {
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .control-label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

        .form-control:focus {
            border-color: #007bff;
            box-shadow: 0 0 8px rgba(0, 123, 255, 0.25);
        }

    .text-danger {
        color: #dc3545;
        font-size: 0.9em;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        transition: background-color 0.3s;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

        .btn-primary:focus {
            outline: none;
        }

    .form-actions {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }
</style>
<h1>Edit Course</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label"></label>
                <input asp-for="DateStart" class="form-control" type="date" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" type="date" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Major" class="control-label"></label>
                <input asp-for="Major" class="form-control" />
                <span asp-validation-for="Major" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lecturer" class="control-label"></label>
                <input asp-for="Lecturer" class="form-control" />
                <span asp-validation-for="Lecturer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input  type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Students" asp-action="ManageStudent">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QLSVVV/Views/Courses/ViewCourse.cshtml
@model IEnumerable<QLSVVV.Models.Course>
<style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f1f1f1;
        color: #444;
        margin: 0;
        padding: 20px;
    }

    h1 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 30px;
    }

    h3 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 30px;
    }

    .search-container {
        text-align: center;
        margin-bottom: 20px;
    }

    .search-input {
        width: 200px;
        padding: 8px;
        border: 2px solid #3498db;
        border-radius: 4px;
        box-sizing: border-box;
        margin-right: 10px;
    }

    .search-btn {
        padding: 8px 16px;
        background-color: #3498db;
        color: #fff;
        border: 2px solid #3498db;
        border-radius: 4px;
        cursor: pointer;
    }

        .search-btn:hover {
            background-color: #fff;
            color: #3498db;
            font-weight: bold;
        }

    p {
        text-align: center;
        margin-bottom: 20px;
    }

        p a {
            display: inline-block;
            padding: 8px 16px;
            background-color: #27ae60;
            color: #fff;
            text-decoration: none;
            border: 2px solid #00CC00;
            border-radius: 4px;
            font-size: 14px;
            transition: background-color 0.3s;
            margin-right: 5px;
        }

            p a:hover {
                background-color: #fff;
                color: #27ae60;
                font-weight: bold;
                text-decoration: none;
            }

    table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 4px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }

    th, td {
        padding: 10px 15px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    thead {
        background-color: #f9f9f9;
    }

    tbody tr:nth-child(even) {
        background-color: #f7f7f7;
    }

    tbody tr:hover {
        background-color: #e9e9e9;
    }

    a {
        color: #3498db;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }

    ul {
        list-style-type: none;
        padding: 0;
        text-align: center;
        margin-top: 20px;
    }

        ul li {
            display: inline-block;
        }

    .btn {
        display: inline-block;
        padding: 8px 16px;
        color: #fff;
        background-color: #3498db;
        text-decoration: none;
        border-radius: 4px;
        transition: background-color 0.3s;
        margin-right: 5px;
    }

        .btn:hover {
            background-color: #fff;
            text-decoration: none;
            color: #3498db;
            font-weight: bold;
        }
</style>
<h1>Hello, Welcome to Course Homepage, Teacher!</h1>

<!-- Search container -->
<div class="search-container">
    <input type="text" id="searchInput" class="search-input" placeholder="Search by Name...">
    <button onclick="search()" class="search-btn">Search</button>
</div>

<!-- Course table -->
<table class="table">
    <!-- Table header -->
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Class</th>
            <th>Date Start</th>
            <th>Date End</th>
            <th>Major</th>
            <th>Lecturer</th>
            <th>Actions</th>
        </tr>
    </thead>
    <!-- Table body -->
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Class</td>
                <td>@item.DateStart?.ToString("d")</td> <!-- Display Date Start -->
                <td>@item.DateEnd?.ToString("d")</td> <!-- Display Date End -->
                <td>@item.Major</td>
                <td>@item.Lecturer</td>
                <td>
                    <a asp-action="ViewStudentlnCourse" asp-route-id="@item.Id">ViewCourse</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<ul>
    <li><a class="btn btn-sm btn-primary" asp-controller="Students" asp-action="Index">Back to HomePage</a></li>
</ul>

<script>
    function search() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.querySelector(".table");
        tr = table.getElementsByTagName("tr");

        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1]; // Search in the second column (Name column)
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>

QLSVVV/Views/Courses/ViewCourseStudent.cshtml
@model IEnumerable<Course>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa;
        color: #333;
        margin: 0;
        padding: 20px;
    }

    h1 {
        color: #2c3e50;
        text-align: center;
        margin-bottom: 30px;
    }

    .search-container {
        text-align: center;
        margin-bottom: 20px;
    }

    .search-input {
        width: 250px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-right: 10px;
    }

    .search-btn {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

        .search-btn:hover {
            background-color: #0056b3;
        }

    .table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 4px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }

        .table th, .table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .table thead {
            background-color: #f8f9fa;
        }

        .table tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table tbody tr:hover {
            background-color: #e9ecef;
        }

    .btn {
        display: inline-block;
        padding: 10px 20px;
        color: #fff;
        background-color: #007bff;
        text-decoration: none;
        border-radius: 4px;
        transition: background-color 0.3s;
        margin-top: 20px;
        text-align: center;
    }

        .btn:hover {
            background-color: #0056b3;
        }

    ul {
        list-style-type: none;
        padding: 0;
        text-align: center;
    }

        ul li {
            display: inline-block;
        }
</style>
<h1>Hello , Welcome to Course Homepage,Student!</h1>

<!-- Search container -->
<div class="search-container">
    <input type="text" id="searchInput" class="search-input" placeholder="Search by Name...">
    <button onclick="search()" class="search-btn">Search</button>
</div>

<table class="table">
    <!-- Table header -->
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Class</th>
            <th>Date Start</th>
            <th>Date End</th>
            <th>Major</th>
            <th>Lecturer</th>
        </tr>
    </thead>
    <!-- Table body -->
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Class</td>
                <td>@item.DateStart?.ToString("d")</td> <!-- Display Date Start -->
                <td>@item.DateEnd?.ToString("d")</td> <!-- Display Date End -->
                <td>@item.Major</td>
                <td>@item.Lecturer</td>
                <td>
                    <a asp-action="ViewStudentlnCourse" asp-route-id="@item.Id">ViewCourse</a>
                </td>
            </tr>
            
        }
    </tbody>
</table>

<ul>

    <li> <a class="btn btn-sm btn-primary" asp-controller="Students" asp-action="Index">Back to HomePage</a></li>
</ul>
<script>
    function search() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.querySelector(".table");
        tr = table.getElementsByTagName("tr");

        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1]; // Search in the second column (Name column)
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>